const $=s=>document.querySelector(s), names={3:'妙蛙花',6:'喷火龙',9:'水箭龟',25:'皮卡丘',65:'胡地',143:'卡比兽'};
let pending=null,selected=[],state=null,busy=false,paused=false,sound=false,ctx=null,nextAudio=0,lastPhase='';
for(const [id,name]of Object.entries(names)){const b=document.createElement('button');b.innerHTML=`${name}<small>Lv.50 · ${ {3:'草 / 毒',6:'火 / 飞行',9:'水',25:'电',65:'超能力',143:'一般'}[id]}</small>`;b.onclick=()=>{const n=+id;if(selected.includes(n))selected=selected.filter(x=>x!==n);else if(selected.length<3)selected.push(n);b.classList.toggle('selected',selected.includes(n));$('#count').textContent=`${selected.length} / 3`;$('#start').disabled=selected.length!==3;};$('#roster').append(b);}
async function api(action,extra={}){if(busy){if(action!=='tick')pending=[action,extra];return;}busy=true;$('#error').textContent='';try{const res=await fetch('/api/dungeon',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:state?.id,revision:state?.revision,audio:sound,...extra})});const data=await res.json();if(!res.ok)throw Error(data.error);state=data;localStorage.setItem('dungeon-run',state.id);render();if(sound&&data.audio)play(data.audio);}catch(e){$('#error').textContent=e.message;paused=true;$('#pause').textContent='继续';}finally{busy=false;if(pending){const p=pending;pending=null;api(...p);}}}
function play(encoded){if(!ctx)return;const raw=atob(encoded),buf=ctx.createBuffer(1,raw.length/2,22050),out=buf.getChannelData(0);for(let i=0;i<out.length;i++){let v=raw.charCodeAt(i*2)|(raw.charCodeAt(i*2+1)<<8);out[i]=(v>32767?v-65536:v)/32768*.55;}const src=ctx.createBufferSource();src.buffer=buf;src.connect(ctx.destination);nextAudio=Math.max(ctx.currentTime+.015,nextAudio);if(nextAudio>ctx.currentTime+.5)nextAudio=ctx.currentTime+.015;src.start(nextAudio);nextAudio+=buf.duration;}
function option(title,desc,choice,disabled=false){const b=document.createElement('button');b.innerHTML=`${title}<small>${desc}</small>`;b.disabled=disabled;b.onclick=()=>api('choose',{choice});$('#choices').append(b);}
function render(){const s=state;document.body.classList.add('playing');$('#setup').hidden=true;$('#game').hidden=false;$('#route').innerHTML=s.nodes.map((n,i)=>`<span class="${i===s.node?'active':i<s.node?'done':''}">${i+1} ${n}</span>`).join('');$('#step').textContent=`节点 ${s.node+1} / 8`;$('#title').textContent=s.nodes[s.node];const hints={battle:'战斗自动进行。C 打开战术菜单，可切换伙伴；A / B 移动光标，C 确认。',reward:'选择一项强化，效果持续到本局结束。',fork:'前方两条路。决定要承受哪一种风险。',camp:'只能选择一次。为下一场战斗保留余力。',won:'森林首领已被击败！本局通关。',lost:'旅程结束。换一种队伍或强化搭配，再来挑战。',retired:'已结束本局。'};$('#hint').textContent=hints[s.phase];$('#controls').hidden=s.phase!=='battle';$('#pause').hidden=s.phase!=='battle';$('#again').hidden=!['won','lost','retired'].includes(s.phase);$('#retire').hidden=!$('#again').hidden;
if(s.phase==='battle'){if(lastPhase!=='battle')$('#scene').innerHTML='<img alt="原生游戏战斗画面">';if(s.image)$('#scene img').src='data:image/png;base64,'+s.image;}else{const symbols={reward:'✦',fork:'↟',camp:'♨',won:'★',lost:'☾',retired:'⌂'};$('#scene').innerHTML=`<div class="interlude"><div class="symbol">${symbols[s.phase]}</div><h2>${{reward:'旅途的馈赠',fork:'选择前路',camp:'片刻休息',won:'秘境征服',lost:'下次再见',retired:'平安归来'}[s.phase]}</h2><p>${s.wins} 场胜利 · ${s.cards.length} 项强化</p><small>生命与异常状态会延续至下一战</small></div>`;}lastPhase=s.phase;
$('#choices').innerHTML='';if(s.phase==='reward')for(const id of s.choices){const c=s.catalog[id];option(c.name,c.description,id);}if(s.phase==='fork'){option('迎战守路者','赢得经验与一次三选一强化',0);option(s.node===1?'穿越荆棘':'搜寻补给',s.node===1?'每只存活伙伴损失 12% 生命，获得一次强化':'恢复 15% 生命，获得树果 ×3，跳过战斗',1);}if(s.phase==='camp'){option('围炉休息',`存活伙伴恢复 ${s.cards.includes(9)?45:25}% 生命`,0);option('救助伙伴','第一只倒下的伙伴复苏，恢复 35% 生命',1,!s.party.some(m=>!m.hp));option('研究秘境','放弃恢复，选择一项强化',2);}
$('#party').innerHTML=s.party.map(m=>`<div class="mon">${names[m.species]} Lv.50<span>${m.hp} / ${m.max_hp}${m.status?' · 异常':''}</span><progress max="${m.max_hp}" value="${m.hp}"></progress></div>`).join('');$('#buffs').innerHTML=s.cards.length?s.cards.map(i=>`<span title="${s.catalog[i].description}">${s.catalog[i].name}</span>`).join(''):'<small>战斗胜利后可获得强化</small>';$('#log').innerHTML=s.log.slice(-6).map(t=>`<div>${t}</div>`).join('');$('#loot').textContent=`体验奖励：经验 ${s.xp}${s.items.length?' · '+s.items.join('、'):''}（不写入正式存档）`;}
$('#start').onclick=()=>{paused=false;lastPhase='';api('new',{selected});};const saved=localStorage.getItem('dungeon-run');$('#resume').hidden=!saved;$('#resume').onclick=()=>{paused=false;api('resume',{id:saved});};$('#sound').onclick=async()=>{sound=!sound;if(sound){ctx??=new AudioContext();await ctx.resume();}else if(ctx)await ctx.suspend();$('#sound').textContent=`声音：${sound?'开启':'关闭'}`;};$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'继续':'暂停';};$('#retire').onclick=()=>api('retire');$('#again').onclick=()=>location.reload();document.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>api('key',{key:+b.dataset.key}));$('#back').onclick=()=>api('key',{key:1,event:3});document.addEventListener('keydown',e=>{if(!state||state.phase!=='battle'||e.repeat)return;const k={ArrowUp:0,ArrowDown:1,Enter:2}[e.key];if(k!==undefined){e.preventDefault();api('key',{key:k});}});setInterval(()=>{if(state?.phase==='battle'&&!paused&&!document.hidden)api('tick');},60);
