// Generated by tools/pipeline/generate_pokemon_names.py. Do not edit.
// Curated facts and per-record sources: data/pokemon_names/gs_legacy.json.
// Dataset SHA256: 7af716b2bc326a66b0e33166362a3881f6fb4b7a8c7d2fc7dc826d3b77591d43
#include <stdatomic.h>
#include <stddef.h>
#include <string.h>

#include "pokemon_names.h"

static atomic_uint_least8_t s_style = POKEMON_NAMES_OFFICIAL;
static const char *const LEGACY[152] = {
    [1] = "巨菇",
    [2] = "阿钱",
    [3] = "西天",
    [4] = "号令",
    [5] = "比斯",
    [6] = "魔鲁",
    [7] = "阿夫",
    [8] = "美兰",
    [9] = "美罗",
    [10] = "美后",
    [11] = "多王",
    [12] = "肥波",
    [13] = "可斯",
    [14] = "皮可",
    [15] = "阿大",
    [16] = "音",
    [17] = "阿童",
    [18] = "阿明",
    [19] = "风雪",
    [20] = "德",
    [21] = "玉风",
    [22] = "玉委",
    [23] = "玉",
    [24] = "玉天",
    [25] = "厄讹",
    [26] = "威克",
    [27] = "威",
    [28] = "吉斯",
    [29] = "地里",
    [30] = "野花",
    [31] = "宇木",
    [32] = "彬木",
    [33] = "古西",
    [34] = "宇西",
    [35] = "崎",
    [36] = "天胆",
    [37] = "莉",
    [38] = "古胆",
    [39] = "花",
    [40] = "江大",
    [41] = "江花",
    [42] = "江天",
    [43] = "江彬",
    [44] = "江灵",
    [45] = "高超",
    [46] = "基",
    [47] = "卡斯",
    [48] = "铁腕",
    [49] = "口呆",
    [50] = "呆兽",
    [51] = "力量",
    [52] = "小火",
    [53] = "催兽",
    [54] = "大钳",
    [55] = "大呆",
    [56] = "耿鬼",
    [57] = "叮叮",
    [58] = "小磁",
    [59] = "磁怪",
    [60] = "三合",
    [61] = "蛋蛋",
    [62] = "卡拉",
    [63] = "椰兽",
    [64] = "沙拉",
    [65] = "古拉",
    [66] = "比拉",
    [67] = "袋兽",
    [68] = "长藤",
    [69] = "阿贝",
    [70] = "立方",
    [71] = "贝立",
    [72] = "石菊",
    [73] = "石怪",
    [74] = "石兽",
    [75] = "万年",
    [76] = "迷你",
    [77] = "卡比",
    [78] = "宝石",
    [79] = "工",
    [80] = "水箭",
    [81] = "芳",
    [82] = "白林",
    [83] = "阿能",
    [84] = "南版",
    [85] = "鲁风",
    [86] = "北口",
    [87] = "品质",
    [88] = "阿兰",
    [89] = "方明",
    [90] = "方红",
    [91] = "方剑",
    [92] = "卡",
    [93] = "地花",
    [94] = "怪花",
    [95] = "路草",
    [96] = "草宝",
    [97] = "合地",
    [98] = "皮",
    [99] = "小波",
    [100] = "阿月",
    [101] = "阿利",
    [102] = "小林",
    [103] = "小雷",
    [104] = "怪兽",
    [105] = "魔怪",
    [106] = "小津",
    [107] = "小森",
    [108] = "阿日",
    [109] = "阿历",
    [110] = "基纳",
    [111] = "山山",
    [112] = "奇草",
    [113] = "呆花",
    [114] = "阿槐",
    [115] = "鬼通",
    [116] = "小狮",
    [117] = "阿柏",
    [118] = "尼多",
    [119] = "多利",
    [120] = "美王",
    [121] = "皮皮",
    [122] = "比超",
    [123] = "比卡",
    [124] = "雷超",
    [125] = "美",
    [126] = "波球",
    [127] = "金刚",
    [128] = "阿音",
    [129] = "玉明",
    [130] = "阿斯",
    [131] = "阿露",
    [132] = "露斯",
    [133] = "布依",
    [134] = "米米",
    [135] = "委比",
    [136] = "毛毛",
    [137] = "哥夫",
    [138] = "吉尼",
    [139] = "三头",
    [140] = "瑞",
    [141] = "野威",
    [142] = "诗",
    [143] = "童童",
    [144] = "兹古",
    [145] = "西木",
    [146] = "阿西",
    [147] = "江明",
    [148] = "江连",
    [149] = "肥大",
    [150] = "灵怪",
    [151] = "斯",
};

bool pokemon_names_set_style(pokemon_name_style_t style)
{
    if (style < POKEMON_NAMES_OFFICIAL || style >= POKEMON_NAMES_STYLE_COUNT) return false;
    atomic_store_explicit(&s_style, (uint_least8_t)style, memory_order_relaxed);
    return true;
}

pokemon_name_style_t pokemon_names_get_style(void)
{
    return (pokemon_name_style_t)atomic_load_explicit(&s_style, memory_order_relaxed);
}

const char *pokemon_names_style_label(void)
{
    return pokemon_names_get_style() == POKEMON_NAMES_GS_LEGACY ? "怀旧" : "官方";
}

const char *pokemon_names_override(uint16_t species, uint8_t *length)
{
    if (length) *length = 0;
    if (pokemon_names_get_style() != POKEMON_NAMES_GS_LEGACY ||
        species < 1 || species >= sizeof(LEGACY)/sizeof(LEGACY[0]) || !LEGACY[species]) return NULL;
    if (length) *length = (uint8_t)strlen(LEGACY[species]);
    return LEGACY[species];
}

uint16_t pokemon_names_legacy_count(void) { return 151; }
