#!/usr/bin/env python3
"""Original trainer portraits plus supported Gen-I status moves and learnsets."""
from pathlib import Path
from PIL import Image
import hashlib,json,sys,subprocess
ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(Path(__file__).parent))
from fetch_gen1 import gen1_move_values,move_zh_name
from convert_moves import GEN1_TYPES,SPECIAL_TYPES
PORTRAITS=['brock','misty','lt_surge','erika','koga','sabrina','blaine','giovanni','lorelei','bruno','agatha','lance','blue','red']
SUPPORTED={14,39,43,45,47,73,74,77,78,79,81,86,92,96,97,105,106,110,111,112,113,115,133,135,137,139,142,151,156,159}
# Deliberately bounded support: do not advertise moves with missing battle effects.
lines=['// Generated by convert_trainers.py; original portrait sources in assets/trainer_sources.json.','#pragma once']
manifest=[]
for id,name in enumerate(PORTRAITS+['chris_back']):
 folder=Path('/tmp/pokecrystal');rel='gfx/trainers/'+name+'.png'
 if name=='chris_back':rel='gfx/player/chris_back.png'
 if not (folder/rel).exists():folder=Path('/tmp/pokered')
 path=folder/rel;im=Image.open(path).convert('RGB');colors=sorted(set(im.getdata()),key=lambda c:sum(c));assert len(colors)==4
 palette=[(r>>3)<<11|(g>>2)<<5|(b>>3) for r,g,b in colors]
 data=[];pix=list(im.getdata())
 for i in range(0,len(pix),4):data.append(sum(colors.index(pix[i+j])<<(6-j*2) for j in range(4)))
 lines.append('static const uint8_t TRAINER_ART_%d[] = {%s};'%(id,','.join(map(str,data))))
 lines.append('static const uint16_t TRAINER_PAL_%d[] = {%s};'%(id,','.join(map(str,palette))))
 manifest.append({'id':id,'name':name,'source':'https://github.com/pret/'+folder.name+'/blob/'+subprocess.check_output(['git','-C',str(folder),'rev-parse','HEAD'],text=True).strip()+'/'+rel,'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'size':im.size})
lines.append('static const uint8_t *const TRAINER_ART[] = {'+','.join('TRAINER_ART_'+str(i) for i in range(15))+'};')
lines.append('static const uint16_t *const TRAINER_PAL[] = {'+','.join('TRAINER_PAL_'+str(i) for i in range(15))+'};')
badge_path=Path('/tmp/pokered/gfx/trainer_card/badges.png')
badge_sheet=Image.open(badge_path).convert('L')
for badge in range(8):
 pix=list(badge_sheet.crop((0,badge*32+16,16,badge*32+32)).getdata())
 data=[sum((pix[i+j]//85)<<(6-j*2) for j in range(4)) for i in range(0,256,4)]
 lines.append('static const uint8_t BADGE_%d[] = {%s};'%(badge,','.join(map(str,data))))
lines.append('static const uint8_t *const BADGE_ART[] = {'+','.join('BADGE_'+str(i) for i in range(8))+'};')
manifest.append({'name':'Kanto badges','source':'https://github.com/pret/pokered/blob/'+subprocess.check_output(['git','-C','/tmp/pokered','rev-parse','HEAD'],text=True).strip()+'/gfx/trainer_card/badges.png','sha256':hashlib.sha256(badge_path.read_bytes()).hexdigest(),'layout':'16px badge rows at y=16+32*i, original gray palette'})
(ROOT/'firmware/main/trainer_assets.h').write_text('\n'.join(lines)+'\n')

lines=['// Supported original status moves; generated from pinned cached PokeAPI values.','#pragma once','static const move_t TRAINER_STATUS_MOVES[] = {']
slug_to_id={}
for id in sorted(SUPPORTED):
 raw=json.loads(Path(f'/tmp/gen1c/cache/move_{id}.json').read_text());v,_=gen1_move_values(raw);name,_=move_zh_name(raw)
 slug_to_id[raw['name']]=id
 lines.append('    {%d,%d,0,%d,%d,%s,"%s",%d},'%(id,GEN1_TYPES.index(v['type']),v['accuracy'] or 255,v['pp'],'true' if v['type'] in SPECIAL_TYPES else 'false',name,len(name.encode())))
lines.append('};')
mons=json.loads(Path('/tmp/gen1c/gen1.json').read_text());learn=[];ranges=[]
for mon in mons:
 start=len(learn)
 for level,slug in mon['learnset']:
  if slug in slug_to_id:learn.append((level,slug_to_id[slug]))
 ranges.append((start,len(learn)-start))
lines.append('static const uint8_t TRAINER_STATUS_LEARN[][2] = {'+','.join('{%d,%d}'%x for x in learn)+'};')
lines.append('static const uint16_t TRAINER_STATUS_RANGES[][2] = {'+','.join('{%d,%d}'%x for x in ranges)+'};')
(ROOT/'firmware/main/trainer_moves.h').write_text('\n'.join(lines)+'\n');print('portraits',len(manifest),'status',len(SUPPORTED),'learn',len(learn))

manifest.append({'name':'supported Gen-I status learnsets','learnset_sha256':hashlib.sha256(Path('/tmp/gen1c/gen1.json').read_bytes()).hexdigest(),'moves':[{'id':i,'source':f'https://pokeapi.co/api/v2/move/{i}/','sha256':hashlib.sha256(Path(f'/tmp/gen1c/cache/move_{i}.json').read_bytes()).hexdigest()} for i in sorted(SUPPORTED)]})
(ROOT/'assets/trainer_sources.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
