#!/usr/bin/env python3
"""Selected Gold/Silver facts; effect implementations live in combat.c."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
rows=json.loads((ROOT/'data/pokemon_moves/selected_gen2.json').read_text())
types='NORMAL FIRE WATER ELECTRIC GRASS ICE FIGHTING POISON GROUND FLYING PSYCHIC BUG ROCK GHOST DRAGON DARK STEEL'.split()
extra=sorted({m['effect'] for m in rows if m['effect'] in ['EFFECT_FLAME_WHEEL','EFFECT_ATTACK_DOWN_2','EFFECT_FALSE_SWIPE','EFFECT_DEFENSE_UP_HIT','EFFECT_ALL_UP_HIT','EFFECT_TWISTER','EFFECT_ACCURACY_DOWN_HIT']})
s=['// Generated by convert_selected_moves.py; pinned Gold/Silver facts.','#pragma once','enum {'+','.join(e+('=100' if i==0 else '') for i,e in enumerate(extra))+'};','static const combat_move_data_t COMBAT_EXTRA[] = {']
for m in rows:
 special=m['type'] in 'FIRE WATER ELECTRIC GRASS ICE PSYCHIC DRAGON DARK'.split();acc=255 if m['effect']=='EFFECT_ALWAYS_HIT' else m['accuracy']
 s.append('{{{%d,%d,%d,%d,%d,%s,"%s",%d},%s,%d}},'%(m['id'],types.index(m['type']),m['power'],acc,m['pp'],str(special).lower(),m['name_zh'],len(m['name_zh'].encode()),m['effect'],m['chance']))
s=[x.replace('{{{','{{').replace('}},','},') for x in s]
s+=['};'];(ROOT/'firmware/main/combat_selected_moves.h').write_text('\n'.join(s)+'\n')
