#!/usr/bin/env python3
"""Pack four original Crystal trainer classes without altering existing art IDs."""
from pathlib import Path
import argparse,hashlib,json,subprocess
from PIL import Image
ROOT=Path(__file__).resolve().parents[2]
p=argparse.ArgumentParser();p.add_argument('--crystal',type=Path,default=Path('/tmp/pokecrystal'));a=p.parse_args()
commit=subprocess.check_output(['git','-C',str(a.crystal),'rev-parse','HEAD'],text=True).strip()
lines=['// Generated by convert_route_trainers.py; see assets/route_trainer_sources.json.','#pragma once'];meta=[]
for i,name in enumerate(('bug_catcher','hiker','fisher','scientist')):
 path=a.crystal/'gfx/trainers'/f'{name}.png';im=Image.open(path).convert('RGB');assert im.size==(56,56)
 colors=sorted(set(im.getdata()),key=sum);assert len(colors)==4
 pix=list(im.getdata());data=[sum(colors.index(pix[j+k])<<(6-k*2) for k in range(4)) for j in range(0,len(pix),4)]
 lines += ['static const uint8_t ROUTE_ART_%u[] = {%s};'%(i,','.join(map(str,data))),'static const uint16_t ROUTE_PAL_%u[] = {%s};'%(i,','.join(str((r>>3)<<11|(g>>2)<<5|(b>>3)) for r,g,b in colors))]
 meta.append({'class':name,'url':f'https://github.com/pret/pokecrystal/blob/{commit}/gfx/trainers/{name}.png','sha256':hashlib.sha256(path.read_bytes()).hexdigest()})
lines+=['static const uint8_t *const ROUTE_TRAINER_ART[]={ROUTE_ART_0,ROUTE_ART_1,ROUTE_ART_2,ROUTE_ART_3};','static const uint16_t *const ROUTE_TRAINER_PAL[]={ROUTE_PAL_0,ROUTE_PAL_1,ROUTE_PAL_2,ROUTE_PAL_3};']
(ROOT/'firmware/main/route_trainer_assets.h').write_text('\n'.join(lines)+'\n');(ROOT/'assets/route_trainer_sources.json').write_text(json.dumps(meta,indent=2)+'\n')
