#!/usr/bin/env python3
"""Compile pinned Crystal music scripts into bounded note streams (not PCM recordings)."""
from pathlib import Path
import argparse,hashlib,json,re,subprocess
ROOT=Path(__file__).resolve().parents[2]
TRACKS=['profoak','elmslab','goldenrodcity','pokemoncenter','route29','gym','kantowildbattle','kantotrainerbattle','kantogymbattle','championbattle','wildpokemonvictory','trainervictory','gymleadervictory','evolution','lookhiker','caughtmon','evolved']
NOTES={x:i for i,x in enumerate(['C_','C#','D_','D#','E_','F_','F#','G_','G#','A_','A#','B_'])}
def parse(path, section=None):
 instructions=[];labels={};scope='';channels=[];tempo=None
 source=path.read_text()
 if section:source=source.split(section+':',1)[1].split('Sfx_MasterBall:' if section=='Sfx_Evolved' else 'Sfx_DexFanfare80109:',1)[0]
 if section=='Sfx_Evolved':tempo=256
 for raw in source.splitlines():
  s=raw.split(';')[0].strip()
  if not s:continue
  if s.endswith(':'):
   label=s[:-1]
   if not label.startswith('.'):scope=label
   labels[scope+label if label.startswith('.') else label]=len(instructions);continue
  op,*tail=s.split(None,1);args=[x.strip() for x in tail[0].split(',')] if tail else []
  if op=='channel':channels.append((int(args[0]) - (4 if section else 0),args[1]))
  if op=='tempo':assert tempo is None or tempo==int(args[0]);tempo=int(args[0])
  instructions.append((op,args,scope))
 assert tempo and channels
 result=[]
 for channel,start in channels:
  pc=labels[start];octave=4;length=12;vol=12;env=2;duty=2;transpose=0;fraction=0
  notes=[];stack=[];loops={};positions={};loop_start=0;looping=False
  for guard in range(40000):
   positions.setdefault(pc,len(notes));op,args,scope=instructions[pc];current=pc;pc+=1
   def label(x):return labels[scope+x if x.startswith('.') else x]
   if op in ('note','rest','drum_note'):
    units=int(args[-1]);duration=units*length*tempo+fraction;frames=duration//256;fraction=duration%256
    assert frames>0,(path,op,args)
    midi=-1 if op=='rest' else (36+int(args[0])%24 if op=='drum_note' else (octave+(1 if channel==3 else 2))*12+NOTES[args[0]]+transpose)
    assert -1<=midi<=127
    notes.append((frames,midi,vol,duty,env));continue
   if op=='octave':octave=int(args[0])
   elif op=='note_type':length,vol,env=map(int,args)
   elif op=='drum_speed':length=int(args[0])
   elif op=='volume_envelope':vol,env=map(int,args)
   elif op=='duty_cycle':duty=int(args[0])
   elif op=='transpose':transpose=-int(args[0])*12+int(args[1])
   elif op=='sound_call':stack.append(pc);pc=label(args[0])
   elif op=='sound_ret':
    if not stack:break
    pc=stack.pop()
   elif op=='sound_loop':
    count=int(args[0]);target=label(args[1])
    if count==0:
     assert not stack and target in positions
     loop_start=positions[target];looping=True;break
    loops[current]=loops.get(current,0)+1
    if loops[current]<count:pc=target
    else:del loops[current]
   elif op not in ('tempo','volume','stereo_panning','vibrato','pitch_offset','pitch_slide','toggle_noise','toggle_sfx','sfx_toggle_noise'):raise ValueError((path,op,args))
  else:raise ValueError('unbounded script '+str(path))
  assert notes and len(notes)<65535
  result.append({'channel':channel,'notes':notes,'loop':loop_start if looping else len(notes)})
 return result

def main():
 ap=argparse.ArgumentParser();ap.add_argument('--source',type=Path,default=Path('/tmp/pokecrystal'));args=ap.parse_args()
 commit=subprocess.check_output(['git','-C',str(args.source),'rev-parse','HEAD'],text=True).strip()
 assert commit=='7a7881d0d62e0ddbd82dcf10e7116807487ac651','music source changed; review before importing'
 out=['// Generated by convert_music.py from pinned pret/pokecrystal; see assets/music_sources.json.','#pragma once']
 manifest={'commit':commit,'source':'https://github.com/pret/pokecrystal','adaptation':'Original note order, channel loops, duty and fixed-point frame durations. Mono synthesis; vibrato, frequency-register detune and pitch slides currently approximated by static note pitch; noise drums use a synthesized kit, wave-channel instrument uses a triangle. Not cycle-accurate Game Boy audio.','tracks':[]}
 for index,name in enumerate(TRACKS):
  path=args.source/('audio/sfx.asm' if name in ('caughtmon','evolved') else f'audio/music/{name}.asm');tracks=parse(path, 'Sfx_CaughtMon' if name in ('caughtmon','evolved') else None)
  for i,t in enumerate(tracks):
   out.append(f'static const music_note_t MUSIC_{index}_{i}[] = {{')
   out.extend('    {%d,%d,%d,%d,%d},'%n for n in t['notes']);out.append('};')
  out.append(f'static const music_track_t MUSIC_TRACK_{index}[] = {{')
  for i,t in enumerate(tracks):out.append(f'    {{MUSIC_{index}_{i}, {len(t["notes"])}, {t["loop"]}, {t["channel"]}}},')
  out.append('};')
  manifest['tracks'].append({'id':index+1,'name':name,'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'channels':[{k:v for k,v in t.items() if k!='notes'}|{'notes':len(t['notes']),'frames':sum(n[0] for n in t['notes'])} for t in tracks]})
 out.append('static const music_score_t MUSIC_SCORES[] = {{0},')
 for i,name in enumerate(TRACKS):out.append(f'    {{"{name}", MUSIC_TRACK_{i}, sizeof(MUSIC_TRACK_{i}) / sizeof(MUSIC_TRACK_{i}[0])}},')
 out.append('};')
 (ROOT/'firmware/main/music_assets.h').write_text('\n'.join(out)+'\n');(ROOT/'assets/music_sources.json').write_text(json.dumps(manifest,indent=2)+'\n')
 print('compiled',len(TRACKS),'scores')
if __name__=='__main__':main()
