#!/usr/bin/env python3
"""Generate the original 151 Crystal base-stat rows from a pinned pret checkout."""
import argparse, hashlib, json, re, subprocess
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--crystal', type=Path, default=Path('/tmp/pokecrystal'))
    a = p.parse_args()
    commit = subprocess.check_output(['git', '-C', str(a.crystal), 'rev-parse', 'HEAD'], text=True).strip()
    paths = re.findall(r'^INCLUDE "(data/pokemon/base_stats/[^\"]+)"', (a.crystal/'data/pokemon/base_stats.asm').read_text(), re.M)[:151]
    assert len(paths) == 151
    rows, sources = [], {}
    for i, path in enumerate(paths, 1):
        raw = (a.crystal/path).read_bytes()
        text = raw.decode()
        stats = re.search(r'^\s*db\s+(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*$', text, re.M)
        assert stats, path
        values = list(map(int, stats.groups()))
        assert all(0 < v < 256 for v in values)
        rows.append(' {' + ','.join(map(str, values)) + '}, // %03d %s' % (i, Path(path).stem))
        sources[path] = hashlib.sha256(raw).hexdigest()
    header = ['// Generated by tools/pipeline/convert_gen2_stats.py.', '// pret/pokecrystal ' + commit, '#pragma once', '// HP, Attack, Defense, Speed, Special Attack, Special Defense.', 'static const uint8_t COMBAT_GEN2_STATS[151][6] = {'] + rows + ['};', '']
    (ROOT/'firmware/main/combat_gen2_stats.h').write_text('\n'.join(header))
    (ROOT/'assets/combat_stats_sources.json').write_text(json.dumps({'repository':'https://github.com/pret/pokecrystal', 'commit':commit, 'species':151, 'stat_order':['hp','attack','defense','speed','special_attack','special_defense'], 'policy':'All DVs 15; stat experience 0; no natures or held-item stat boosts.', 'files_sha256':sources}, indent=2)+'\n')
    print('Generated 151 six-stat rows from', commit)

if __name__ == '__main__':
    main()
