#!/usr/bin/env python3
"""Build exact 2bpp OAM composites from a pinned pret/pokegold checkout.

python3 tools/pipeline/convert_battle_fx.py --src /tmp/pokegold
python3 tools/pipeline/convert_battle_fx.py --src /tmp/pokegold --check

Requires Pillow only at generation time. Source bytes must match the pinned Git
tree; no images are drawn/recolored here. Firmware trajectories/palettes are
project adaptations and do not claim to emulate the original battle engine.
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
from pathlib import Path
import re
import subprocess

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
COMMIT = "656583c939d30f920a316177311a502dd222b57c"
SOURCE_URL = f"https://github.com/pret/pokegold/tree/{COMMIT}"
# key, graphic sheet, frameset label, index among its oamframe commands.
SELECTION = (
    ("hit", "hit", "Hit", 0), ("hit_big", "hit", "HitBig", 0),
    ("punch", "hit", "Punch", 0), ("kick", "hit", "Kick", 0),
    ("palm", "hit", "Palm", 0), ("fang", "hit", "Fang", 0),
    ("fire0", "fire", "Ember", 0), ("fire1", "fire", "Ember", 1),
    ("water0", "water", "WaterGun1", 0), ("water1", "water", "WaterGun3", 0),
    ("ice", "ice", "Ice", 0),
    ("leaf0", "plant", "RazorLeaf1", 0), ("leaf1", "plant", "RazorLeaf2", 1),
    ("rock", "rocks", "SmallRock", 0), ("boulder", "rocks", "BigRock", 0),
    ("poison", "poison", "SludgeBubble", 1),
    ("bubble", "bubble", "SmallBubble", 0),
    ("wind0", "wind", "Gust", 0), ("wind1", "wind", "Gust", 1),
    ("wave0", "psychic", "Wave", 0), ("wave1", "psychic", "Wave", 1),
    ("bind", "rope", "Bind1", 0), ("whip", "whip", "VineWhip1", 1),
    ("cut", "cut", "CutDownLeft", 2), ("cut_long", "cut", "CutLongDownLeft", 5),
    ("star", "objects", "Star", 0),
    ("horn", "horn", "Horn", 0), ("needle", "horn", "Needle", 0),
    ("lick", "water", "Lick", 2),
    ("core", "explosion", "ThunderShockCore", 0),
    ("spark0", "lightning", "ThunderShockSparks", 0),
    ("spark1", "lightning", "ThunderShockSparks", 1),
    ("thunder", "lightning", "ThunderLeft", 3),
    ("charge", "charge", "ChargeOrb2", 0),
    ("orb", "egg", "BarrageBall", 0),
    ("dragon_rage", "fire", "DragonRage", 0),
    ("globe", "globe", "SeismicToss", 0),
    ("hydro0", "water", "HydroPump", 0),
    ("hydro1", "water", "HydroPump", 2),
    ("hydro2", "water", "HydroPump", 4),
    ("beam", "beam", "Beam", 1),
    ("beam_tip", "beam", "BeamTip", 0),
    ("explosion0", "explosion", "Explosion", 0),
    ("explosion1", "explosion", "Explosion", 1),
    ("explosion2", "explosion", "Explosion", 2),
)


def number(value: str) -> int:
    return int(value[1:], 16) if value.startswith("$") else int(value)


def block(source: str, label: str) -> str:
    match = re.search(r"^" + re.escape(label) + r":\s*\n(.*?)(?=^\.[\w]+:|\Z)", source, re.M | re.S)
    if not match:
        raise ValueError(f"source label missing: {label}")
    return match.group(1)


def build(src: Path) -> tuple[str, dict]:
    paths = {"data/battle_anims/framesets.asm", "data/battle_anims/oam.asm", "macros/gfx.asm",
             "data/moves/animations.asm", "engine/battle_anims/bg_effects.asm"}
    paths.update(f"gfx/battle_anims/{gfx}.png" for _, gfx, _, _ in SELECTION)
    files, hashes = {}, {}
    for path in sorted(paths):
        expected = subprocess.check_output(["git", "-C", str(src), "show", f"{COMMIT}:{path}"])
        actual = (src / path).read_bytes()
        if actual != expected:
            raise ValueError(f"{path} differs from pinned {COMMIT}")
        files[path], hashes[path] = actual, hashlib.sha256(actual).hexdigest()
    framesets = files["data/battle_anims/framesets.asm"].decode()
    oam = files["data/battle_anims/oam.asm"].decode()
    table = {}
    for offset, count, ptr, key in re.findall(r"battleanimoam\s+(\$[0-9a-f]+),\s*(\d+),\s*(\.\w+)\s*; BATTLE_ANIM_OAMSET_(\w+)", oam, re.I):
        table[key] = (number(offset), int(count), ptr)
    out = ["// Generated by tools/pipeline/convert_battle_fx.py; do not edit.",
           f"// Source: {SOURCE_URL}",
           "// Exact PNG grayscale + OAM tile positions/flips; 3 = transparent.",
           "#pragma once", "#include <stdint.h>",
           "typedef struct { const uint8_t *data; uint8_t w, h; } battle_fx_art_t;", ""]
    manifest = dict(repository="https://github.com/pret/pokegold", commit=COMMIT,
                    sources=hashes, sprites=[])
    for key, gfx, frameset, frame_index in SELECTION:
        rows = re.findall(r"oamframe BATTLE_ANIM_OAMSET_(\w+),\s*\d+([^\n]*)", block(framesets, ".Frameset_" + frameset))
        oam_key, frame_flags = rows[frame_index]
        tile_base, count, ptr = table[oam_key]
        parts = []
        for raw in re.findall(r"dbsprite\s+([^\n]+)", block(oam, ptr))[:count]:
            vals = [v.strip() for v in raw.split(";", 1)[0].split(",")]
            xt, yt, xp, yp, tile = map(number, vals[:5])
            parts.append((xt * 8 + xp, yt * 8 + yp, tile_base + tile,
                          "OAM_XFLIP" in vals[5], "OAM_YFLIP" in vals[5]))
        assert len(parts) == count
        left, top = min(p[0] for p in parts), min(p[1] for p in parts)
        width = max(p[0] + 8 for p in parts) - left
        height = max(p[1] + 8 for p in parts) - top
        assert 0 < width <= 64 and 0 < height <= 64, (key, width, height)
        sheet = Image.open(io.BytesIO(files[f"gfx/battle_anims/{gfx}.png"])).convert("L")
        assert sheet.width % 8 == 0 and sheet.height % 8 == 0
        tiles_per_row = sheet.width // 8
        pixels = [[3] * width for _ in range(height)]
        # Lower OAM indices have priority; transparent pixels leave the prior
        # layer untouched. Reversing the list reproduces that overlap priority.
        for ox, oy, tile, xflip, yflip in reversed(parts):
            tx, ty = (tile % tiles_per_row) * 8, (tile // tiles_per_row) * 8
            assert ty + 8 <= sheet.height, (key, tile, sheet.size)
            for y in range(8):
                for x in range(8):
                    value = sheet.getpixel((tx + (7 - x if xflip else x), ty + (7 - y if yflip else y)))
                    assert value in (0, 85, 170, 255)
                    if value != 255:
                        pixels[oy - top + y][ox - left + x] = value // 85
        if "B_OAM_XFLIP" in frame_flags:
            pixels = [row[::-1] for row in pixels]
        if "B_OAM_YFLIP" in frame_flags:
            pixels.reverse()
        encoded = bytearray()
        for row in pixels:
            for x in range(0, width, 4):
                group = row[x:x + 4] + [3] * max(0, x + 4 - width)
                encoded.append(sum(v << (6 - i * 2) for i, v in enumerate(group)))
        # Independent unpack sanity: widths need not be a multiple of four.
        stride = (width + 3) // 4
        assert [[(encoded[y * stride + x // 4] >> (6 - (x % 4) * 2)) & 3
                 for x in range(width)] for y in range(height)] == pixels
        out.append(f"// {gfx}.png / Frameset_{frameset}[{frame_index}] / OAMSET_{oam_key}: {width}x{height}")
        out.append(f"static const uint8_t fx_art_{key}[] = {{")
        for i in range(0, len(encoded), 16):
            out.append("    " + ", ".join(f"0x{v:02x}" for v in encoded[i:i + 16]) + ",")
        out.append("};")
        manifest["sprites"].append(dict(key=key, sheet=gfx, frameset=frameset, frame=frame_index,
                                        oam_set=oam_key, width=width, height=height,
                                        bytes=len(encoded), sha256=hashlib.sha256(encoded).hexdigest()))
    out.append("enum {")
    out.extend(f"    FX_ART_{key.upper()}," for key, _, _, _ in SELECTION)
    out.extend(["    FX_ART_COUNT", "};", "static const battle_fx_art_t FX_ART[FX_ART_COUNT] = {"])
    out.extend(f"    {{fx_art_{s['key']}, {s['width']}, {s['height']}}}," for s in manifest["sprites"])
    out.extend(["};", ""])
    manifest["total_bytes"] = sum(s["bytes"] for s in manifest["sprites"])
    return "\n".join(out), manifest


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", type=Path, required=True)
    ap.add_argument("--out", type=Path, default=ROOT / "firmware/main/battle_fx_assets.h")
    ap.add_argument("--manifest", type=Path, default=ROOT / "assets/battle_fx_sources.json")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    header, manifest = build(args.src)
    encoded_manifest = json.dumps(manifest, indent=2) + "\n"
    if args.check:
        assert args.out.read_text() == header, "generated header is stale"
        assert args.manifest.read_text() == encoded_manifest, "source manifest is stale"
    else:
        args.out.write_text(header)
        args.manifest.write_text(encoded_manifest)
    print(f"{'verified' if args.check else 'generated'} {len(manifest['sprites'])} OAM sprites, {manifest['total_bytes']} B; {COMMIT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
