#!/usr/bin/env python3
"""Compile original Crystal mechanics and all Gen1 level-up skills from local pinned sources."""
import argparse,json,re,hashlib
from pathlib import Path
from fetch_gen1 import gen1_move_values,move_zh_name
from convert_moves import GEN1_TYPES,SPECIAL_TYPES
ROOT=Path(__file__).resolve().parents[2]
p=argparse.ArgumentParser();p.add_argument('--source',type=Path,default=Path('/tmp/gen1c'));p.add_argument('--crystal',type=Path,default=Path('/tmp/pokecrystal'));a=p.parse_args()
rows=[re.split(r',\s*',l.split(';')[0].strip()[5:]) for l in (a.crystal/'data/moves/moves.asm').read_text().splitlines() if l.strip().startswith('move ')][:165]
assert len(rows)==165
effects=sorted({r[1] for r in rows});out=['// Generated by convert_combat_moves.py; Crystal 7a7881d0d62e0ddbd82dcf10e7116807487ac651.','#pragma once','enum {'+','.join(effects)+'};','typedef struct { move_t move; uint8_t effect,chance; } combat_move_data_t;','static const combat_move_data_t COMBAT_DATA[165] = {']
slugs={}
for i,r in enumerate(rows,1):
 raw=json.loads((a.source/f'cache/move_{i}.json').read_text());v,_=gen1_move_values(raw);zh,_=move_zh_name(raw);assert zh
 ty=r[3].lower();ty=ty if ty in GEN1_TYPES else v['type'];assert ty in GEN1_TYPES
 slugs[raw['name']]=i
 out.append('{{%d,%d,%s,%s,%s,%s,%s,%d},%s,%s},'%(i,GEN1_TYPES.index(ty),r[2],'255' if r[1]=='EFFECT_ALWAYS_HIT' or int(r[4])==0 else r[4],r[5],'true' if ty in SPECIAL_TYPES else 'false',json.dumps(zh,ensure_ascii=False),len(zh.encode()),r[1],r[6]))
out+=['};','static const uint8_t COMBAT_PARENTS[151] = {']
mons=json.loads((a.source/'gen1.json').read_text());parents=[];by_slug={m['slug']:m['id'] for m in mons}
for m in mons:
 raw=json.loads((a.source/f"cache/pokemon-species_{m['id']}.json").read_text());parent=raw.get('evolves_from_species');parents.append(by_slug.get(parent['name'],0) if parent else 0)
out += [','.join(map(str,parents)),'};'];learn=[];ranges=[]
for m in mons:
 rec=sorted({(lv,slugs[slug]) for lv,slug in m['learnset'] if slug in slugs});ranges.append((len(learn),len(rec)));learn+=rec
out+=['static const uint16_t COMBAT_LEARN_RANGES[151][2] = {'+','.join('{%d,%d}'%r for r in ranges)+'};','static const uint8_t COMBAT_LEARN[][2] = {'+','.join('{%d,%d}'%r for r in learn)+'};']
(ROOT/'firmware/main/combat_moves.h').write_text('\n'.join(out)+'\n')
(ROOT/'assets/combat_sources.json').write_text(json.dumps({'moves':165,'effects':len(effects),'levelup_records':len(learn),'learned_rule':'All level-eligible moves, including pre-evolution forms, deduplicated; no PP or forgetting','crystal_commit':'7a7881d0d62e0ddbd82dcf10e7116807487ac651','source_sha256':hashlib.sha256((a.crystal/'data/moves/moves.asm').read_bytes()).hexdigest(),'type_adaptation':'Dark/Steel moves use pre-retcon types in the existing 15-type game.'},ensure_ascii=False,indent=2)+'\n')
print('moves',165,'effects',len(effects),'learn records',len(learn))
