#!/usr/bin/env python3
"""Build the curated, source-attributed Gold/Silver name table (offline)."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "data/pokemon_names/gs_legacy.json"
OUTPUT = ROOT / "firmware/main/pokemon_names.c"


def generate() -> str:
    raw = DATA.read_bytes()
    document = json.loads(raw)
    records = document["records"]
    sources = {source["id"] for source in document["sources"]}
    ids = [record["id"] for record in records]
    if len(ids) != len(set(ids)) or any(type(sid) is not int or not 1 <= sid <= 151 for sid in ids):
        raise ValueError("legacy name IDs must be unique within 1..151")
    lines = []
    for record in sorted(records, key=lambda row: row["id"]):
        name = record["name"]
        if not name or len(name.encode()) > 15 or not all("\u4e00" <= char <= "\u9fff" for char in name):
            raise ValueError(f"invalid legacy display name: {record['id']}")
        if not record["sources"] or not set(record["sources"]) <= sources:
            raise ValueError(f"missing source for species {record['id']}")
        lines.append(f'    [{record["id"]}] = "{name}",')
    return f'''// Generated by tools/pipeline/generate_pokemon_names.py. Do not edit.
// Curated facts and per-record sources: data/pokemon_names/gs_legacy.json.
// Dataset SHA256: {hashlib.sha256(raw).hexdigest()}
#include <stdatomic.h>
#include <stddef.h>
#include <string.h>

#include "pokemon_names.h"

static atomic_uint_least8_t s_style = POKEMON_NAMES_OFFICIAL;
static const char *const LEGACY[152] = {{
{chr(10).join(lines)}
}};

bool pokemon_names_set_style(pokemon_name_style_t style)
{{
    if (style < POKEMON_NAMES_OFFICIAL || style >= POKEMON_NAMES_STYLE_COUNT) return false;
    atomic_store_explicit(&s_style, (uint_least8_t)style, memory_order_relaxed);
    return true;
}}

pokemon_name_style_t pokemon_names_get_style(void)
{{
    return (pokemon_name_style_t)atomic_load_explicit(&s_style, memory_order_relaxed);
}}

const char *pokemon_names_style_label(void)
{{
    return pokemon_names_get_style() == POKEMON_NAMES_GS_LEGACY ? "怀旧" : "官方";
}}

const char *pokemon_names_override(uint16_t species, uint8_t *length)
{{
    if (length) *length = 0;
    if (pokemon_names_get_style() != POKEMON_NAMES_GS_LEGACY ||
        species < 1 || species >= sizeof(LEGACY)/sizeof(LEGACY[0]) || !LEGACY[species]) return NULL;
    if (length) *length = (uint8_t)strlen(LEGACY[species]);
    return LEGACY[species];
}}

uint16_t pokemon_names_legacy_count(void) {{ return {len(records)}; }}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != source:
            raise SystemExit("pokemon_names.c is stale; run generate_pokemon_names.py")
    else:
        OUTPUT.write_text(source)
    print(f"{'checked' if args.check else 'generated'} {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
