import { CATALOG } from './catalog.js';
const sections = [['home','游戏介绍'],['start','开始冒险'],['pokemon','宝可梦图鉴'],['explore','探索路线'],['items','道具手册'],['care','照料与体能'],['battle','战斗与经验'],['moves','技能招式'],['evolution','进化指南'],['party','队伍与仓库'],['challenge','道馆与联盟'],['dungeon','秘境副本'],['achievements','成就奖励'],['shiny','闪光与连携'],['settings','设备设置'],['save','备份与升级'],['updates','版本更新']];
const types = ['一般','火','水','电','草','冰','格斗','毒','地面','飞行','超能力','虫','岩石','幽灵','龙','恶','钢'];
let data = CATALOG.release;
let typeFilter = '';
const content = document.querySelector('#content');
const search = document.querySelector('#search');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mon = id => data.pokemon.find(p => p.id === Number(id));
const item = id => id == null ? undefined : data.items.find(p => p.id === Number(id));
const sprite = id => `<canvas class="sprite" data-mon="${id}" width="64" height="64" aria-hidden="true"></canvas>`;
const chip = id => `<a class="chip" href="#pokemon/${id}">${esc(mon(id)?.name || id)}</a>`;
const chips = ids => `<div class="chip-list">${[...new Set(ids)].map(chip).join('')}</div>`;
const itemLink = id => `<a href="#items/${id}">${esc(item(id)?.name || id)}</a>`;
const title = (name, lead = '', over = 'POKEWALK / FIELD NOTES') => `<header class="page-heading"><p class="eyebrow">${esc(over)}</p><h1>${esc(name)}</h1><p class="lead">${lead}</p></header>`;
const block = (name, body) => `<section class="chapter"><h2>${esc(name)}</h2>${body}</section>`;
const note = body => `<aside class="callout">${body}</aside>`;
const table = (heads, rows) => `<div class="table-wrap"><table><thead><tr>${heads.map(h => `<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const numbered = rows => `<ol class="steps">${rows.map(([a,b]) => `<li><strong>${a}</strong><p>${b}</p></li>`).join('')}</ol>`;
const versionNote = () => `<p class="version-note">GitHub 发布版：${esc(data.version)}。社区可下载版本以社区审核结果为准。</p>`;
const atlas = new Image(); atlas.src = 'pokemon.png';
function drawSprites() { if (!atlas.complete || !atlas.naturalWidth) return; for (const c of content.querySelectorAll('canvas[data-mon]')) { const n = Number(c.dataset.mon)-1; const ctx=c.getContext('2d'); ctx.imageSmoothingEnabled=false; ctx.clearRect(0,0,64,64); ctx.drawImage(atlas,(n%16)*64,Math.floor(n/16)*64,64,64,0,0,64,64); } }
atlas.addEventListener('load',drawSprites);
function home() { return `${versionNote()}<section class="hero"><div><p class="eyebrow">A LITTLE ADVENTURE, EVERY DAY</p><h1>把关都<br>装进口袋。</h1><p class="lead">带一只伙伴，慢慢长大。<br>在 ESP32 掌机上照料、探索、捕获，沿着徽章之路挑战更强的对手，再带自己的队伍走进秘境。</p><div class="hero-links"><a class="primary-link" href="#start">开始你的冒险 →</a><a class="secondary-link" href="#pokemon">查找宝可梦</a></div></div><figure><img src="battle.png" width="240" height="320" alt="PokeWalk 宣传封面：皮卡丘与暴鲤龙对战"><figcaption>皮卡丘与暴鲤龙的原宣传画面。<br>按键以当前版说明为准；电子宠物养成、自动对战与肉鸽秘境持续更新。</figcaption></figure></section><div class="numbers"><div><b>151</b><span>第一世代宝可梦</span></div><div><b>12</b><span>探索地图</span></div><div><b>10</b><span>秘境主题</span></div><div><b>16</b><span>成就目标</span></div></div>${[['01','相遇之后，还有成长','喂食、玩耍、学会招式与进化。图鉴记录你遇见过的伙伴，仓库保存每一只捕获的宝可梦。','care','看看照料有什么用'],['02','熟悉的路，也有新发现','徽章活动、追踪目标、地区分支和深层探索，把寻找伙伴变成一段旅程。','explore','选择下一条路线'],['03','每段冒险，都值得保存','换游戏或更新固件前，通过 USB 把进度备份到自己的电脑，再按需导入恢复。','save','保存我的冒险']].map(([n,h,p,l,a])=>`<section class="chapter-intro"><span class="num">${n}</span><div><h2>${h}</h2><p>${p}</p><a href="#${l}">${a} →</a></div></section>`).join('')}${note('这是玩家制作的同人硬件游戏。宝可梦角色与原作素材的权利属于各自权利人；本手册介绍本项目的实现，规则与原作并不完全相同。')}`; }
function start() { return title('第一次冒险','从大木博士的介绍开始，选一个愿意陪你走下去的伙伴。')+numbered([['准备设备','为兼容的 AI Passport / ESP32-C3 设备安装 PokeWalk。已有进度时，先看<a href="#save">备份与升级</a>，完整安装可能清空存档。'],['选择初始伙伴','妙蛙种子、小火龙、杰尼龟、皮卡丘，四选一。之后仍可以通过探索或进化补齐其他伙伴。'+chips([1,4,7,25])],['认识三枚按键','A 向上，B 向下，C 确认。长按 B 返回；长按 C 熄屏。屏幕休眠后的第一次按键用于唤醒。'],['去探索','选择地图与路线，主动探索消耗 5 点体能。遇到宝可梦后，可以直接尝试捕获，也可以先战斗降低它的 HP。'],['开始徽章之旅','完成一次野生战斗胜利后，挑战第一座道馆。随徽章推进解锁活动、地图与更强的对手。']])+note('体能按时间恢复，约 1 小时从 0 恢复到 100。先照料伙伴、挑选队伍，再把体能用在想去的地方。'); }
function pokemon(id) { const p=mon(id); if (p) return pokemonDetail(p); const list=data.pokemon.filter(p=>typeFilter==='' || p.type.includes(Number(typeFilter))); return title('151 次相遇','点开任意宝可梦，查询常驻路线、章节限制、进化方式和自动学会的技能。')+`<div class="section-tools"><label for="type-filter">按属性筛选</label><select id="type-filter"><option value="">全部属性</option>${types.map((t,i)=>`<option value="${i}" ${typeFilter===String(i)?'selected':''}>${t}</option>`).join('')}</select><span class="count">${list.length} / 151</span></div><div class="mon-grid">${list.map(p=>`<a class="mon" href="#pokemon/${p.id}"><small>No.${String(p.id).padStart(3,'0')}</small>${sprite(p.id)}<strong>${esc(p.name)}</strong><span>${p.type.filter(t=>types[t]).map(t=>types[t]).join(' / ')} · ${'★'.repeat(p.rarity)}</span></a>`).join('')}</div>`; }
function pokemonDetail(p) { const maps=data.maps.filter(m=>m.pool.includes(p.id)); const guests=data.maps.filter(m=>m.visitors?.includes(p.id)); const badge=data.activities.filter(a=>a.pool.includes(p.id)); const rewards=data.maps.filter(m=>m.trails?.some(t=>t.rewards.includes(p.id))); const evos=data.items.flatMap(i=>i.evolutions.filter(e=>e[0]===p.id).map(e=>`${itemLink(i.id)} → ${chip(e[1])}`)); const prior=data.pokemon.filter(m=>m.evolveTo===p.id).map(m=>chip(m.id)); return `<a class="backlink" href="#pokemon">← 全部宝可梦</a><div class="detail-head">${sprite(p.id)}<div><p class="eyebrow">NO.${String(p.id).padStart(3,'0')}</p><h1>${esc(p.name)}</h1><div class="badges"><span class="tag">${p.type.filter(t=>types[t]).map(t=>types[t]).join(' / ')}</span><span class="tag warm">${'★'.repeat(p.rarity)}</span></div></div></div>`+block('在哪里寻找',`<p>物种解锁条件：<b>${esc(data.chapters[p.chapter]?.condition || '随剧情解锁')}</b>。还需要满足地图自身的开放条件；出现在池中不代表每次都能遇到。</p>`+table(['常驻地图','分支'],maps.map(m=>[`<a href="#explore/${m.id}">${esc(m.name)}</a>`, m.trails ? m.trails.filter(t=>t.pool.includes(p.id)).map(t=>esc(t.name)).join('、') : '基础路线']))+(guests.length?`<p>开发版轮换访客：${guests.map(m=>`<a href="#explore/${m.id}">${esc(m.name)}</a>`).join('、')}。轮到它时才会加入该分支的遇敌池。</p>`:'')+`<p>也可在图鉴中追踪已解锁的目标，前往对应基础生态路线收集线索；章节条件仍然生效。</p>`)+block('其他获取途径',`${badge.length?'<p>徽章活动：'+badge.map(a=>esc(a.name)).join('、')+'。获得相应徽章后开放，物种章节限制仍生效。</p>':''}${rewards.length?'<p>地区秘境通关候选：'+rewards.map(m=>esc(m.dungeon)).join('、')+'。所选分支改变通关伙伴池。</p>':''}${!badge.length&&!rewards.length?'<p>优先参考上方常驻路线、图鉴追踪和进化途径。</p>':''}`)+block('如何进化',`<p>${p.evolveTo?`${p.evolveLevel?`达到 Lv.${p.evolveLevel}`:'满足进化条件'} → ${chip(p.evolveTo)}，在照料页面确认进化。`:'没有普通等级进化。'}</p>${evos.length?`<div class="chip-list">${evos.join('　')}</div>`:''}${prior.length?`<p>前一阶段：${prior.join('、')}。</p>`:''}<p><a href="#evolution">查看完整进化规则 →</a></p>`)+block('成长技能',`<p>学会的技能都会保留，自动从已学技能中选择，不设四技能栏或 PP。以下是本项目的学习等级，包含简化后的经典机器招式。</p>`+table(['等级','招式','属性','威力'],p.learnset.map(([id,lv])=>{const m=data.moves.find(m=>m.id===id);return [`Lv.${lv}`,esc(m?.name||id),esc(types[m?.type]||'—'),m?.power||'变化'];})))+`<p class="fine">捕获参数 ${p.catchRate} 用于窗口计算，不是直接成功百分比。体重 ${(p.weight/10).toFixed(1)} kg，影响沉重球等效果。</p>`; }
function routeCard(m) { const levels=m.levels!=null?`Lv.${m.levels[0]}–${m.levels[1]}`:''; return `<article class="route"><p class="route-meta">REGION ${String(m.id+1).padStart(2,'0')} ${levels}</p><h2><a href="#explore/${m.id}">${esc(m.name)}</a></h2><p>${esc(m.description)}${m.condition?' · '+esc(m.condition):''}</p>${m.levels!=null?`<p>普通：Lv.${m.levels[0]}–${m.levels[1]}；深层：Lv.${m.deepMin}–${m.levels[1]}。</p>`:'<p>基础生态路线：遇敌等级会参考当前伙伴与剧情进度。</p>'}<details open><summary>常驻宝可梦 · ${m.pool.length} 种</summary>${chips(m.pool)}</details>${m.trails?`<details><summary>查看三个分支</summary>${m.trails.map(t=>`<div class="trail"><b>${esc(t.name)}</b><p>${esc(t.description||'')}</p>${chips(t.pool)}<p>该分支秘境通关伙伴：</p>${chips(t.rewards)}</div>`).join('')}</details>`:''}${m.visitors?.length?`<details><summary>轮换访客 · ${m.visitors.length} 种候选</summary><p>每个分支当前加入其中 2 种，完成 12 次本地图探索后轮换；还需达到物种章节条件。</p>${chips(m.visitors)}</details>`:''}</article>`; }
function explore(id) { const focus=data.maps.find(m=>m.id===id); const maps=focus?[focus]:data.maps; return title(focus?focus.name:'沿着地图走一走','常驻物种决定地图的性格，分支改变遇敌范围；徽章和研究进度把旅程继续往前推。')+versionNote()+ (focus?'<a class="backlink" href="#explore">← 全部地图</a>':'')+`<div class="route-list">${maps.map(routeCard).join('')}</div>`+block('地图、等级和深层',`<p>新增地区按自己的等级区间随机生成，换低等级伙伴也不会降低该地图的野生等级。深层需要先完成该地区的发现进度；进入后使用更高等级范围和奖励。</p><p>原有四条生态路线覆盖全部第一世代的常驻候选，但高稀有物种还受徽章、联盟和赤红等章节限制。图鉴追踪用于集中寻找某个目标，不会提前解锁章节。</p>`)+block('每枚徽章带来的活动',table(['活动','线索 / 等级','奖励','候选伙伴'],data.activities.map(a=>[esc(a.name),`${esc(a.story)}<br>Lv.${a.level}–${a.level+2}`,itemLink(a.item),chips(a.pool)])))+block('地区研究与追踪',`<p>各地区记录发现、捕获和追踪进度，满足研究条件后领取一次性奖励，并逐步开放地区秘境和深层。请按游戏内研究面板的具体条件完成。</p><p>图鉴追踪积累 3 条线索后安排目标遭遇。地区面板也会显示当地追踪目标；完成当前目标后才进入下一轮，切页不会刷新掉目标。</p>`)+(data.features.careEvents?block('轮换访客与伙伴发现',`<p>8 张扩展地图新增主题访客。每个分支同时有 2 种，按该地图累计探索次数轮换；离开页面、换地图、关机再开都保留进度。一次有效探索就计数，保存失败不计。</p><p>每次探索有 <b>12% + 心情 ÷ 5</b>（向下取整，最高 32%）的特殊发现机会；在相应结果上触发：</p>`+table(['发现','作用'],[['伙伴发现补给','线索事件额外得到最多 2 个树果；背包满时只加入剩余容量。'],['伙伴特训','发现宝可梦时额外获得相当于基础经验 50% 的经验，再应用养成倍率；重复物种也能获得。'],['闪光踪迹','本次新生成遭遇增加一次独立闪光判定，普通探索基础闪光率由 1/48 约提高到 1/24，再叠加探索连携。']])):note('切换到“开发体验版”，可查看本次新增的轮换访客、伙伴特训和闪光踪迹。')); }
function itemSources(i) { const a=data.achievements.filter(a=>a.item===i.id); const b=data.activities.filter(a=>a.item===i.id); return [i.kind===0?'野生战斗掉落（球种受敌方稀有度影响）':'战斗随机掉落、秘境与探索奖励',...a.map(a=>`成就「${esc(a.name)}」×${a.quantity}`),...b.map(a=>`徽章活动「${esc(a.name)}」`)].join('；'); }
function items(id) { const i=item(id); if(i)return title(i.name,esc(i.description))+block('获取与使用',`<p>${itemSources(i)}。</p><p>背包容量：${i.capacity}。在道具页按当前用途使用；进化类道具需要选择符合条件的伙伴。</p>${i.evolutions.length?table(['使用对象','进化结果'],i.evolutions.map(([a,b])=>[chip(a),chip(b)])):''}`)+note('高稀有敌人更适合寻找高阶球和特殊进化道具。成就奖励到达容量后仍可领取，多余数量不会保留。')+'<a href="#items">← 全部道具</a>'; return title('道具手册','球、进化石、进化机器与养成补给。点开道具查看效果、容量和对应成就。')+`<div class="item-list">${data.items.map(i=>`<article class="item-row"><span class="item-number">${String(i.id+1).padStart(2,'0')}</span><div><h2><a href="#items/${i.id}">${esc(i.name)}</a></h2><p>${esc(i.description)}</p><p>${itemSources(i)}</p></div><span class="tag">最多 ${i.capacity}</span></article>`).join('')}</div>`+block('补给不只是精灵球',`<p>野生战斗、训练家、徽章活动、成就和秘境共同提供道具。进化机器并非开局基础掉落；大师球等高阶奖励也有更严格的敌人稀有度条件。</p>${data.features.careEvents?'<p>本版每次野生战斗胜利都有基础掉落，70% 为球类；敌人稀有度越高，高阶球和进化道具越常见。满仓时优先转为有空间的基础补给。</p>':''}<p>哞哞牛奶在战斗中回复至少 50 HP，或最大 HP 的一半（取较高值），不超过 HP 上限。成长后的伙伴也能用得上。</p>`); }
function care() { return title('把照料变成旅途的帮助','不增加每日任务。吃饱、心情好、亲密度高，都能在原有的冒险里发挥作用。')+versionNote()+block('喂食、玩耍与补给',table(['操作','收益','消耗'],[['喂食','饱食 +30，心情 +5','树果 ×1'],['玩耍','心情 +15，亲密度 +1','5 点体能；不足时不能玩耍'],['开心饼干','心情 +25，亲密度 +2','开心饼干 ×1']]))+`<section class="calc"><h2>看看当前养成加成</h2><p class="fine">拖动数值，仅作规则演示，不读取你的存档。</p><div class="calc-grid">${[['satiety','饱食',80],['mood','心情',70],['bond','亲密度',30]].map(([k,n,v])=>`<label for="${k}">${n}<input id="${k}" type="range" min="0" max="100" value="${v}"><span id="${k}-value">${v}</span></label>`).join('')}</div><output id="care-output" aria-live="polite"></output><p id="care-detail"></p></section>`+block('三种正向联系',data.features.careEvents?table(['状态','具体作用'],[['吃饱与亲密','经验倍率 = 100% + 饱食÷4 + 心情÷10 + 亲密度÷5，各项向下取整，最高 155%。'],['好心情','特殊发现机会 = 12% + 心情÷5，最高 32%。决定探索时更容易遇到补给、特训或闪光踪迹。'],['亲密度','捕获窗口额外扩大 亲密度÷2%，最高 +50%。与原有心情、球种、敌方 HP 共同计算，并受窗口上限约束。']]):'<p>已发布版的经验倍率由饱食、心情、亲密度共同决定，范围 80%–130%。心情影响捕获窗口，综合养成状态也会提高探索的稀有倾向。10 月 6 日版在这些基础上增强联动。</p>')+block('体能是一套公共资源','<p>探索、训练家、挑战、秘境入场和玩耍共用体能；战斗中的 HP 是另一回事。体能每 36 秒恢复约 1 点，0 到 100 约 1 小时。食物不直接恢复体能。</p><p>关机时间要能通过校准后的真实时间计算，才会补回离线恢复量。建议在设置里完成 Wi-Fi 时间校准。亮屏在线和关机后的时间计算路径不同。</p>')+block('状态会慢慢变化','<p>饱食和心情随时间下降；陪伴会积累亲密度。严重低落会影响战斗表现。你可以随时回来喂食、玩耍，再继续探索，没有每日打卡要求。</p>'); }
function battle() { return title('打得过，就打。想留下，就捕获。','战斗自动选择已学技能，保留出招的不确定性，并提高伤害技能的选择倾向。')+block('野生遭遇的两种选择',table(['选择','后续'],[['直接捕获','在蓝色窗口内投球。失败后对方攻击一次，再回到选择；可以继续尝试、战斗或逃跑。'],['进入战斗','自动对战直到胜负或成功逃跑。胜利后只给一次捕获机会，没抓到就会逃走。'],['逃跑','根据双方状态计算成功机会；失败时对手会攻击，随后可再次尝试。']]))+block('经验从哪里来','<p>野生战斗胜利、失败和捕获都有经验，只是比例不同。发现新的物种、训练家挑战、地区研究、秘境也能帮助成长。经验再按养成状态调整。</p><p>队伍参战成员分享经验，后备伙伴也有部分收益；较低等级伙伴有追赶机制。升级学会技能时会提示，已学技能一直保留。等级上限为 100。</p>')+block('训练家对战','<p>挑战前可以选择出场伙伴。战斗中换宠和恢复操作会占用回合；只有更换的一方播放投球出场动画。战败会影响养成状态，但不会倒扣经验。</p>')+note('捕获不是另一次隐藏的命中投骰：主要看投球时是否命中屏幕显示的窗口。球种、心情、亲密度与敌人状态决定窗口宽度。'); }
function moves() { return title('招式图录',`当前数据收录 ${data.moves.length} 个招式。学会的技能全部保留，自动出招，不需要分配四个技能位或补 PP。`)+note('本项目覆盖第一世代伙伴可用的成长与经典机器招式，并非照搬原作的全部学习路径。到宝可梦详情页可以查每一只的学习等级。')+table(['编号','招式','属性','威力','基础命中'],data.moves.map(m=>[m.id,esc(m.name),esc(types[m.type]),m.power||'变化',m.accuracy===255?'必中':`${m.accuracy}%`])); }
function evolution() { const level=data.pokemon.filter(p=>p.evolveTo&&p.evolveLevel); const stones=data.items.filter(i=>i.evolutions.length); return title('到了那一天，就一起进化','等级达标后，在照料页面确认进化；不再把普通等级进化卡在额外亲密度门槛上。')+block('等级进化',table(['伙伴','要求','下一阶段'],level.map(p=>[chip(p.id),`Lv.${p.evolveLevel}`,chip(p.evolveTo)])))+block('道具进化',table(['道具','适用伙伴'],stones.map(i=>[itemLink(i.id),i.evolutions.map(([a,b])=>`${chip(a)} → ${chip(b)}`).join('<br>')])))+note('成长机器不会跳过等级要求。通讯类进化使用本项目设计的进化机器，省去连接交换的步骤。进化保留原伙伴的等级、经验和闪光属性。'); }
function party() { return title('自己的队伍，自己的出场','最多六只伙伴组成队伍，仓库保存更多捕获的宝可梦。')+block('换入与换出','<p>在队伍与仓库页面选择伙伴。队伍已满时，先换出一只再换入；正在秘境中时会提示是否结束本次秘境，确认后才允许调整。</p><p>仓库提供筛选、排序、闪光标志与详情入口。先按闪光或等级筛选，再看伙伴详情，会比逐只翻找快。</p>')+block('让队伍参与探索','<p>队伍里的不同物种与生态匹配时，会提供探索加成。森林偏草／虫，山地偏岩石／地面，水域偏水／冰，电站偏电／毒；同种伙伴不会无限叠加。</p><p>秘境入场从自己的伙伴中选择队员。升级后的技能和属性会带进新的挑战，因此养成与阵容选择都能影响副本体验。</p>')+block('培养后备伙伴','<p>后备队员也能分享一部分战斗经验，低等级成员有追赶收益。不必为了每只伙伴都练级而反复手动更换技能。</p>'); }
function challenge() { return title('八枚徽章之后，还没有结束','道馆、四天王、冠军与赤红，按挑战进度依次开放。')+table(['挑战者','徽章 / 主题','阵容'],data.trainers.map(t=>[esc(t.name),esc(t.badge),t.team.map((id,n)=>`${chip(id)} ${t.levels[n]?`Lv.${t.levels[n]}`:''}`).join('<br>')]))+block('挑战需要什么',table(['挑战','体能消耗 / 开放'],[['路线训练家','每次 5 点；更强训练家随徽章开放。'],['道馆 / 赤红','每次 10 点；第一道馆需要一次野生战斗胜利，后续顺序开放。'],['联盟','入场 20 点，同一轮后续战斗不重复收入场费。'],['秘境','入场 20 点，进入后沿节点推进。']]))+block('胜利之后','<p>首胜有对话、徽章或道具奖励，并开放对应活动。联盟之后还有更强的重战与赤红；新的地图和秘境为后期队伍提供进一步的成长目标。</p>'); }
function dungeon() { return title('带自己的伙伴，走一段未知的路','选择出场伙伴，沿节点战斗、拿奖励、选增益。在一次挑战中建立自己的打法。')+block('一次秘境怎么走',numbered([['选队入场','从已有伙伴中选最多三只，消耗 20 点体能。角色成长和阵容选择在这里延续。'],['推进节点','秘境按节点推进，面对普通敌人、精英和首领；获得经验、道具并挑选本轮增益。'],['继续，或带着收获离开','可以保存进度稍后继续。调整外部队伍时需要先结束秘境，游戏会给确认。'],['通关后的相遇','通关后发现可捕获的秘境伙伴，进入遭遇列表。遭遇满时需要腾出位置再领取，不会为了塞入奖励直接丢掉伙伴。']]))+block('地区秘境',table(['主题','关联地图','地区等级参考'],[['常青试炼','基础秘境','随伙伴成长'],...data.maps.filter(m=>m.dungeon).map(m=>[esc(m.dungeon),`<a href="#explore/${m.id}">${esc(m.name)}</a>`,`Lv.${m.levels[0]}–${m.levels[1]}`]),['冠军秘境','冠军与八地区研究进度','Lv.70–100']]))+block('本轮增益',table(['增益','作用'],data.cards.map(([n,d])=>[esc(n),esc(d)])))+note('地图和秘境的开放条件不同。查看游戏内的研究与秘境面板，完成首通后还可尝试更高难度的挑战模式。'); }
function achievements() { return title('把里程碑带回背包','捕获、进化、闪光、图鉴与挑战的记录，变成继续冒险的补给。')+table(['成就','条件','奖励'],data.achievements.map(a=>[esc(a.name),esc(a.description),`${itemLink(a.item)} ×${a.quantity}`]))+note('道具已满也可以完成领取。实际加入的数量受背包上限限制，溢出部分不会保留；想拿齐奖励时可以先使用一些道具。'); }
function shiny() { return title('寻找颜色不同的那一次相遇','闪光概率按获取途径区分，不只绑定物种稀有度；低星伙伴也值得寻找。')+versionNote()+table(['途径','基础概率'],['普通遭遇通道','主动探索','徽章活动','秘境伙伴'].map((s,i)=>[s,`1/${data.shiny[i]} · ${(100/data.shiny[i]).toFixed(2)}%`]))+note('这是生成新伙伴时的概率，不影响已经在遭遇列表中的个体。普通遭遇通道指底层遭遇来源，不表示站着不动就一定持续刷新。')+(data.features.careEvents?block('探索连携','<p>只有探索野生战斗胜利增加连携。离开页面、换地图、关机重启会保留；去道馆或秘境的胜负不影响它。逃跑不增加、不清零。</p><p><b>探索战败，或确认开始捕获，会中断连携。</b>有连携时点击捕获会二次确认。已生成的闪光伙伴不会因清零而变回普通。</p><p>连胜越多，下次新发现的闪光概率越高。普通探索使用公式 (连胜 + 48) ÷ (连胜 + 2304)，持续提升但不直接保证每次闪光。</p><div class="calc"><label for="wins">探索连胜次数</label><input id="wins" type="number" min="0" max="4294967295" value="20"><output id="shiny-output" aria-live="polite"></output><p class="fine">闪光踪迹还会叠加独立判定；计算器展示普通探索。</p></div>'):'<p>10 月 6 日版新增探索连携，以及养成联动的“闪光踪迹”；可切换攻略版本查看。</p>')+(data.features.shinyEntry?block('闪光出场','<p>出场动作完成后追加短暂反色、八向星光与闪光音效。野生、训练家和秘境均支持；只对真正换入的一方播放，双方闪光依次展示，静音时不发声。</p>'):'')+block('抓到之后','<p>闪光会记录在仓库、图鉴与成就进度中，进化和存档恢复保留闪光属性。获得一只、收集多种闪光都有对应成就奖励。</p>'); }
function settings() { return title('按自己的节奏玩','声音、亮度和休眠，让掌机适合白天带走，也适合夜里安静放着。')+table(['设置 / 功能','说明'],[['声音','静音开关和音量调节；遇敌、稀有与闪光会有不同提示音。'],['亮度','屏幕亮度可调；长按 C 熄屏，空闲 60 秒自动熄屏。'],['电量','可开关电量显示，只在菜单和照料页名字附近显示，减少遮挡。'],['时间校准','通过 Wi-Fi 校准时间，用于离线体能与时钟相关逻辑。'],['名称翻译',data.features.nostalgicMoves?'菜单 → 选项 → 译名切换官方／怀旧。肥大怀旧版同时切换 191 种招式名称；战斗文字、技能列表和学招提示联动，效果与编号不变。旧译依据历史资料整理，可随时切回官方名。':'可切换宝可梦名称版本，包含旧译名风格；图鉴编号和实际物种不变。'],['游戏时长',data.features.careEvents?'累计亮屏游戏时长，今天和明天会相加；旧版未记录的历史时间无法补算。':'10 月 6 日版新增累计游戏时长记录。'],['存档','USB 备份、导入与设备确认；详见备份与升级页面。']] ); }
function save() { return title('让升级继续原来的冒险','先把进度留在自己的电脑，再决定更新或换游戏。')+`<div class="hero-links"><a class="primary-link" href="../">打开存档管理 →</a><a class="secondary-link" href="https://github.com/Luobata/ESP32-PokemonGo/releases">获取发布包 ↗</a></div>`+block('完整安装和保档更新不是同一件事',`<p>社区完整安装包或 full.bin 可能覆盖存档区域，安装同一种游戏也不例外。更新前备份，安装后可导入恢复。</p><p>PokeWalk-update.zip 用于分区匹配的现有设备，只更新应用区。按包内工具检查分区、备份和写后校验；两种方式都需要 USB 连接。</p>`)+numbered([['打开工具并连接 USB','用桌面 Chrome / Edge 打开存档管理页，选择私人备份目录，再连接设备。内网 HTTP 页面需要先下载离线工具，在 localhost 启动。'],['在设备发起备份','菜单 → 选项 → 备份存档。等待网页完成写入与回读校验，保留原来的 .pksave 文件。'],['安装或更新固件','按发布包说明操作。不要把完整安装当作保档更新，也不要在写入中断电。'],['需要时导入恢复','设备进入导入存档，网页选择文件。设备确认后，先备份当前进度，收到确认才开始写入。'],['重启后核对','重新连接，等待导入结果核对，并在设备确认伙伴、等级与图鉴。网页读懂备份不等于已经导入成功。']])+block('当前兼容范围',`<p>${data.features.careEvents?'10 月 6 日固件支持 V5–V20 来源存档；V5–V19 按版本迁移，V20 可导出再导入。':'2026.10.05 地区扩展固件支持 V5–V18 来源存档。' } 构建哈希不同不再单独构成网页导入拒绝条件；仍要求同一设备、分区匹配、内容校验和固件能实际解码该版本。</p><p>不支持把新格式倒灌到不认识它的旧固件。开发命令 restore.py 仍要求同设备、同构建。遇到兼容问题，应同时升级固件、刷新网页或重新下载离线工具。</p>`)+note('网页不会上传存档，也不需要登录。请把备份保存在私人目录，勿公开分享原始 NVS 或 .pksave。'); }
function updates() { const rows=[['2026.10.07','闪光出场与怀旧招式译名','闪光伙伴出场追加反色与八向星光，按实际换入的一方播放；肥大怀旧版同步切换全部 191 种招式名。存档仍为 V20，支持 V5–V20 来源。','GitHub 版本 v2026.10.07-shiny-names；游戏新内容需更新固件，社区版以审核结果为准'],['2026.10.06','轮换、特殊发现与养成联动','8 张扩展地图的分支加入轮换访客；新增补给、特训、闪光踪迹；照料页展示具体加成。本手册与存档工具互通入口。','GitHub 版本 v2026.10.06-exploration；社区版以审核结果为准'],['2026.10.06','探索平衡与累积时长','地图最低等级、道具分布、探索连携与捕获确认；累计亮屏游戏时长。','已合并到 10.06 发布包，保留 V5–V20 存档迁移'],['2026.10.05','第一世代地区扩展','新增地区与分支、地区研究、主题秘境及后期挑战；完善旧存档迁移。','GitHub 版本 v2026.10.05-expansion'],['2026.10.04–05','存档恢复与补给修复','解除不必要的构建哈希限制，补全旧版本迁移与导入结果核对；哞哞牛奶改为随最大 HP 提升恢复量。','实际兼容范围以每份发布说明为准'],['2026.10.03','电量、奖励与闪光','菜单与照料页显示电量；道具达到上限仍可领成就；按不同获取途径提高闪光概率，秘境通关增加伙伴奖励。','历史更新'],['更早版本','从口袋宠物到关都冒险','完善金银风格战斗、捕获、队伍仓库、进化、道馆联盟、秘境、声音与休眠；加入 USB 存档备份和保档更新工具。','历史功能概览']];return title('冒险还在继续','按版本查看变化；上方可以切换当前版与 10 月 6 日版攻略。')+`<div class="timeline">${rows.map(([d,h,p,s])=>`<article class="release"><p class="release-date">${d}</p><div><h2>${h}</h2><p>${p}</p><p class="fine">${s}</p></div></article>`).join('')}</div>`+`<p><a href="https://github.com/Luobata/ESP32-PokemonGo/releases">下载与完整发布记录 ↗</a></p><p class="fine">当前攻略数据来源：<code>${esc(data.sourceRef)}</code>。图鉴、道具、招式、路线和成就由该版本固件数据生成；人工说明随版本检查。</p>`; }
const pages={home,start,pokemon,explore,items,care,battle,moves,evolution,party,challenge,dungeon,achievements,shiny,settings,save,updates};
function searchResults(q) { const key=q.toLowerCase(); const matches=[]; const add=(label,kind,href,extra='')=>{if(`${label} ${extra}`.toLowerCase().includes(key))matches.push({label,kind,href});}; for(const [id,n] of sections)add(n,'攻略',`#${id}`);for(const p of data.pokemon)add(p.name,'宝可梦',`#pokemon/${p.id}`,String(p.id).padStart(3,'0'));for(const i of data.items)add(i.name,'道具',`#items/${i.id}`,i.description);for(const m of data.maps)add(m.name,'地图',`#explore/${m.id}`,m.description);for(const a of data.achievements)add(a.name,'成就','#achievements',a.description);for(const m of data.moves)add(m.name,'招式','#moves');return title(`查找：${q}`,`${matches.length} 个匹配结果`)+(matches.length?`<div class="result-list">${matches.map(r=>`<a class="result-row" href="${r.href}"><span>${esc(r.label)}</span><span class="tag">${r.kind}</span></a>`).join('')}</div>`:'<p class="empty">没有找到。可以试试图鉴编号、正式名称、道具或玩法名称。</p>'); }
function calculators() { if(document.querySelector('#satiety')) { const s=Number(document.querySelector('#satiety').value),m=Number(document.querySelector('#mood').value),b=Number(document.querySelector('#bond').value);for(const [id,v] of [['satiety',s],['mood',m],['bond',b]])document.querySelector(`#${id}-value`).textContent=v;const xp=data.features.careEvents?100+Math.floor(s/4)+Math.floor(m/10)+Math.floor(b/5):80+Math.floor((s+m)/5)+Math.floor(b/10);document.querySelector('#care-output').textContent=`经验倍率 ${xp}%`;document.querySelector('#care-detail').textContent=data.features.careEvents?`特殊发现机会 ${12+Math.floor(m/5)}% · 亲密度额外扩大捕获窗口 ${Math.floor(b/2)}%`:'已发布版：心情与球种、敌方状态一起影响捕获窗口。'; } if(document.querySelector('#wins')) {const w=Math.max(0,Math.min(4294967295,Number(document.querySelector('#wins').value)||0));document.querySelector('#shiny-output').textContent=`下次普通探索约 ${(100*(w+48)/(w+2304)).toFixed(2)}%`; } }
function render() { const [raw,idText]=(location.hash.slice(1)||'home').split('/');const section=pages[raw]?raw:'home';const id=idText===undefined?null:Number(idText);document.querySelector('#navigation').innerHTML=sections.map(([key,name],n)=>`<a href="#${key}" ${section===key&&!search.value?'aria-current="page"':''}>${name}<span class="nav-number">${String(n+1).padStart(2,'0')}</span></a>`).join('');content.innerHTML=search.value.trim()?searchResults(search.value.trim()):pages[section](id);document.title=`${sections.find(s=>s[0]===section)[1]} · PokeWalk`;drawSprites();calculators(); }
document.querySelector('#version').addEventListener('change',e=>{data=CATALOG[e.target.value];render();});search.addEventListener('input',render);content.addEventListener('change',e=>{if(e.target.id==='type-filter'){typeFilter=e.target.value;render();document.querySelector('#type-filter').focus();}});content.addEventListener('input',calculators);content.addEventListener('click',e=>{const link=e.target.closest?.('a[href^="#"]');if(link&&link.getAttribute('href')===location.hash&&search.value){search.value='';render();content.focus();}});window.addEventListener('hashchange',()=>{if(location.hash==='#content'){content.focus();return;}search.value='';typeFilter='';render();content.focus({preventScroll:true});content.scrollIntoView({block:'start'});});render();
